// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQCThpcm-iKsEvnvtDzauBiwjP0ZOovn0',
    appId: '1:463015067154:web:5d64e973bac0187002a2cb',
    messagingSenderId: '463015067154',
    projectId: 'archives-zzzz',
    authDomain: 'archives-zzzz.firebaseapp.com',
    databaseURL: 'https://archives-zzzz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'archives-zzzz.firebasestorage.app',
    measurementId: 'G-WE6QQYDV55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7e_KVtt7d23sJEoynUSFqtV_Tckcii10',
    appId: '1:463015067154:android:602f1ebffbe4c41f02a2cb',
    messagingSenderId: '463015067154',
    projectId: 'archives-zzzz',
    databaseURL: 'https://archives-zzzz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'archives-zzzz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0_csBMIO1clfKIryqaCCTv5w9sRY1lWI',
    appId: '1:463015067154:ios:97b60f1aa7cd601e02a2cb',
    messagingSenderId: '463015067154',
    projectId: 'archives-zzzz',
    databaseURL: 'https://archives-zzzz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'archives-zzzz.firebasestorage.app',
    iosBundleId: 'com.example.archives',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0_csBMIO1clfKIryqaCCTv5w9sRY1lWI',
    appId: '1:463015067154:ios:97b60f1aa7cd601e02a2cb',
    messagingSenderId: '463015067154',
    projectId: 'archives-zzzz',
    databaseURL: 'https://archives-zzzz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'archives-zzzz.firebasestorage.app',
    iosBundleId: 'com.example.archives',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQCThpcm-iKsEvnvtDzauBiwjP0ZOovn0',
    appId: '1:463015067154:web:e32686f0651ac82502a2cb',
    messagingSenderId: '463015067154',
    projectId: 'archives-zzzz',
    authDomain: 'archives-zzzz.firebaseapp.com',
    databaseURL: 'https://archives-zzzz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'archives-zzzz.firebasestorage.app',
    measurementId: 'G-T539DW5K7S',
  );

}